service/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

urlpatterns = [
    path('maintenances/', MaintenanceListView.as_view(), name='maintenance_list'),
    path('claims/', ClaimListView.as_view(), name='claim_list'),
    path('car/<pk>/maintenances', MaintenanceCarListView.as_view(), name='car_maintenance'),
    path('car/<pk>/claims', ClaimCarListView.as_view(), name='car_claim'),
    path('maintenance/create', MaintenanceCreateView.as_view(), name='maintenance_create'),
    path('claim/create', ClaimCreateView.as_view(), name='claim_create'),
    path('maintenance/<pk>/update', MaintenanceUpdateView.as_view(), name='maintenance_update'),
    path('claim/<pk>/update', ClaimUpdateView.as_view(), name='claim_update'),
    path('maintenance/<pk>/delete', MaintenanceDeleteView.as_view(), name='maintenance_delete'),
    path('claim/<pk>/delete', ClaimDeleteView.as_view(), name='claim_delete'),
    path('maintenance/<pk>/description/<atribute>', MaintenanceDescriptionView.as_view(),  name='maintenance_description'),
    path('claim/<pk>/description/<atribute>', ClaimDescriptionView.as_view(), name='claim_description'),
    path('api/maintenances/', MaintenanceListAPI.as_view(), name='maintenance_list_api'),
    path('api/<user>/maintenances/', MaintenanceUserListAPI.as_view(), name='user_maintenance_list_api'),
    path('api/maintenance/<pk>/', MaintenanceDetailAPI.as_view(), name='maintenance_detail_api'),
    path('api/claims/', ClaimListAPI.as_view(), name='claim_list_api'),
    path('api/<user>/claims/', ClaimUserListAPI.as_view(), name='user_claim_list_api'),
    path('api/claim/<pk>/', ClaimDetailAPI.as_view(), name='claim_detail_api'),
]

silant_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('service.urls')),
    path('', include('forklifts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

service/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User
from forklifts.models import AutoCar, UserAcc


class Maintenance(models.Model):
    maintenance_type = models.ForeignKey('MaintenanceType', on_delete=models.CASCADE, verbose_name='Вид ТО')
    maintenance_date = models.DateField(default=datetime.now, verbose_name='Дата проведения ТО')
    operating_time = models.PositiveIntegerField(default=0, verbose_name='Наработка, м/час')
    work_order_number = models.CharField(max_length=32, verbose_name='Заказ-наряд')
    work_order_date = models.DateField(default=datetime.now, verbose_name='дата заказ-наряда')
    service_company = models.ForeignKey('ServiceCompany', on_delete=models.CASCADE, verbose_name='Организация, проводившая ТО', null=True, blank=True)
    autocar = models.ForeignKey(AutoCar, on_delete=models.CASCADE, verbose_name='Заводской номер погрузчика')

    def __str__(self):
        return f'{self.maintenance_date} {self.autocar}'

    class Meta:
        verbose_name = 'Техническое обслуживание'
        verbose_name_plural = 'Технические обслуживания'


class Claim(models.Model):
    failure_date = models.DateField(default=datetime.now, verbose_name='Дата отказа')
    operating_time = models.PositiveIntegerField(default=0, verbose_name='Наработка, м/час')
    failure_node = models.ForeignKey('FailureNode', on_delete=models.CASCADE, verbose_name='Узел отказа')
    failure_description = models.TextField(blank=True, null=True,  verbose_name='Описание отказа')
    recovery_method = models.ForeignKey('RecoveryMethod', on_delete=models.CASCADE, verbose_name='Способ восстановления')
    spare_parts = models.TextField(blank=True, null=True, verbose_name='Используемые запасные части')
    recovery_date = models.DateField(default=datetime.now, verbose_name='Дата восстановления')
    autocar = models.ForeignKey(AutoCar, on_delete=models.CASCADE, verbose_name='Заводской номер погрузчика') 
    service_company = models.ForeignKey('ServiceCompany', on_delete=models.CASCADE, verbose_name='Сервисная компания', null=True, blank=True)       

    def __str__(self):
        return f'{self.failure_date} {self.autocar}'

    def downtime(self):
        deltatime = self.recovery_date - self.failure_date
        return deltatime.days

    class Meta:
        verbose_name = 'Рекламация'
        verbose_name_plural = 'Рекламации'

# Словари

class MaintenanceType(models.Model):
    name = models.CharField(max_length=50, verbose_name='Название')
    description = models.TextField(verbose_name='Описание', blank=True, null=True)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Вид технического обслуживания'
        verbose_name_plural = 'Виды технического обслуживания'  


class FailureNode(models.Model):
    name = models.CharField(max_length=100, verbose_name='Название')
    description = models.TextField(verbose_name='Описание', blank=True, null=True)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Узел отказа'
        verbose_name_plural = 'Узлы отказа' 


class RecoveryMethod(models.Model):
    name = models.CharField(max_length=100, verbose_name='Название')
    description = models.TextField(verbose_name='Описание', blank=True, null=True)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Способ восстановления'
        verbose_name_plural = 'Способы восстановления'


class ServiceCompany(models.Model):
    name = models.CharField(max_length=200, verbose_name='Название')
    description = models.TextField(verbose_name='Описание', blank=True, null=True)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Сервисная компания'
        verbose_name_plural = 'Сервисные компании'   

service/forms.py
from django import forms
from .models import *

class MaintenanceForm(forms.ModelForm):
    class Meta:
        model = Maintenance
        fields = '__all__'
        widgets ={
            'type': forms.RadioSelect()
        }

class ClaimForm(forms.ModelForm):
    class Meta:
        model = Claim
        fields = '__all__'

service/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from forklifts.models import *
from service.models import *
from service.forms import *
from service.serializers import MaintenanceSerializer, ClaimSerializer
from django.contrib.auth.mixins import PermissionRequiredMixin
from rest_framework import generics


class MaintenanceListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    permission_required = 'service.view_maintenance'
    model = Maintenance
    template_name = 'service/maintenance_list.html'

    def get_queryset(self):
        if not self.request.user.is_staff:
            user = User.objects.get(pk=self.request.user.pk)
            try:
                profile = UserAcc.objects.get(user=user)
                if profile.is_service:
                    return Maintenance.objects.filter(service_company=profile.service_company)
            except:
                return Maintenance.objects.filter(autocar__client=user)
        else:
            return Maintenance.objects.all()
        

class MaintenanceCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    permission_required = 'service.add_maintenance'
    model = Maintenance
    form_class = MaintenanceForm
    template_name = 'service/maintenance_create.html'
    success_url = reverse_lazy('maintenance_list')


class MaintenanceUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    permission_required = 'service.change_maintenance'
    model = Maintenance
    form_class = MaintenanceForm
    template_name = 'service/maintenance_update.html'
    success_url = reverse_lazy('maintenance_list')


class MaintenanceDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    permission_required = 'service.delete_maintenance'
    model = Maintenance
    template_name_suffix = '_confirm_delete'
    success_url = reverse_lazy('maintenance_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["type"] = 'maintenance'
        return context
    

class MaintenanceCarListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    permission_required = 'service.view_maintenance'
    model = Maintenance
    template_name = 'service/maintenance_car.html'

    def get_queryset(self):
        car = AutoCar.objects.get(pk=self.kwargs["pk"])
        return Maintenance.objects.filter(autocar=car)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["car"] = AutoCar.objects.get(pk=self.kwargs["pk"])
        return context     


class ClaimListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    permission_required = 'service.view_claim'
    model = Claim
    template_name = 'service/claim_list.html'

    def get_queryset(self):
        if not self.request.user.is_staff:
            user = User.objects.get(pk=self.request.user.pk)
            try:
                profile = UserAcc.objects.get(user=user)
                if profile.is_service:
                    return Claim.objects.filter(service_company=profile.service_company)
            except:
                return Claim.objects.filter(autocar__client=user)
        else:
            return Claim.objects.all()  


class ClaimCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    permission_required = 'service.add_claim'
    model = Claim
    form_class = ClaimForm
    template_name = 'service/claim_create.html'
    success_url = reverse_lazy('claim_list') 


class ClaimUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    permission_required = 'service.change_claim'
    model = Claim
    form_class = ClaimForm
    template_name = 'service/claim_update.html'
    success_url = reverse_lazy('claim_list')   


class ClaimDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    permission_required = 'service.delete_claim'
    model = Claim
    template_name_suffix = '_confirm_delete'
    success_url = reverse_lazy('claim_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["type"] = 'claim'
        return context 


class ClaimCarListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    permission_required = 'service.view_claim'
    model = Claim
    template_name = 'service/claim_car.html'

    def get_queryset(self):
        car = AutoCar.objects.get(pk=self.kwargs["pk"])
        return Claim.objects.filter(autocar=car)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["car"] = AutoCar.objects.get(pk=self.kwargs["pk"])
        return context  


class MaintenanceDescriptionView(TemplateView):
    template_name = 'service/modal_description.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        maintenance = Maintenance.objects.get(pk=self.kwargs["pk"])
        atribute = context['atribute']
        if atribute == 'maintenance_type':
            context['atribute'] = maintenance.maintenance_type
            context['description'] = maintenance.maintenance_type.description
        elif atribute == 'service_company':
            context['atribute'] = maintenance.service_company
            context['description'] = maintenance.service_company.description
        return context  


class ClaimDescriptionView(TemplateView):
    template_name = 'service/modal_description.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        claim = Claim.objects.get(pk=self.kwargs["pk"])
        atribute = context['atribute']
        if atribute == 'failure_node':
            context['atribute'] = claim.failure_node
            context['description'] = claim.failure_node.description
        elif atribute == 'recovery_method':
            context['atribute'] = claim.recovery_method
            context['description'] = claim.recovery_method.description
        elif atribute == 'service_company':
            context['atribute'] = claim.service_company
            context['description'] = claim.service_company.description
        return context 


# API
class MaintenanceListAPI(generics.ListAPIView):
    serializer_class = MaintenanceSerializer
    queryset = Maintenance.objects.all()


class MaintenanceUserListAPI(generics.ListAPIView):
    serializer_class = MaintenanceSerializer

    def get_queryset(self):
        try:
            user = int(self.kwargs['user'])
        except:
            user = self.kwargs['user']
        if type(user) == int:
            queryset = Maintenance.objects.filter(autocar__client=user)
        elif type(user) == str:
            queryset = Maintenance.objects.filter(autocar__client__username=user)
        return queryset 


class MaintenanceDetailAPI(generics.RetrieveAPIView):
    serializer_class = MaintenanceSerializer

    def get_object(self):
        obj = Maintenance.objects.get(pk=self.kwargs['pk'])
        return obj


class ClaimListAPI(generics.ListAPIView):
    serializer_class = ClaimSerializer
    queryset = Claim.objects.all() 


class ClaimUserListAPI(generics.ListAPIView):
    serializer_class = ClaimSerializer

    def get_queryset(self):
        try:
            user = int(self.kwargs['user'])
        except:
            user = self.kwargs['user']
        if type(user) == int:
            queryset = Claim.objects.filter(autocar__client=user)
        elif type(user) == str:
            queryset = Claim.objects.filter(autocar__client__username=user)
        return queryset


class ClaimDetailAPI(generics.RetrieveAPIView):
    serializer_class = ClaimSerializer

    def get_object(self):
        obj = Claim.objects.get(pk=self.kwargs['pk'])
        return obj                              

service/templates/service/claim_car.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<a class="back-page" href="{% url 'car_list' %}"><i class="fas fa-long-arrow-alt-left"></i>Назад</a>
<div class="client">
    <i class="silant silant-vehicle"></i>
    <h2>Погрузчик {{car.serial_number}}</h2>
</div>
<h3>Информация о комплектации и технических характеристиках Вашей техники</h3>
<nav class="nav-panel">
    <ul>
        <li><a href="{% url 'car_detail' car.pk %}"><i class="silant silant-service"></i> Информация</a></li>
        <li><a href="{% url 'car_maintenance' car.pk %}"><i class="silant silant-maintenance"></i> ТО</a></li>
        <li class="active"><a href="{% url 'car_claim' car.pk %}"><i class="silant silant-complaint"></i> Рекламации</a></li>
    </ul>
</nav>
{% if user.is_superuser or user.groups.first.name == "Сервисная организация" or user.groups.first.name == "Менеджер" %}
<div class="action-buttons">
    <a href="{% url 'claim_create' %}">Создать рекламацию</a>
</div>
{% endif %}
<section class="area-table"> 
<table id="tableComplaints" class="datatable" data-order='[0, "desc"]'>
    <thead class="datatable-thead">
        <tr>
            <th width="30%">Дата отказа</th>
            <th width="20%">Наработка, м/час</th>
            <th width="40%">Узел отказа</th>
            <th width="30%">Описание отказа</th>
            <th width="20%">Способ восстановления</th>
            <th width="20%">Используемые запасные части</th>
            <th width="30%">Дата восстановления</th>
            <th width="20%">Время простоя техники</th>
            <th width="30%">Сервисная компания</th>
            {% if user.is_superuser or user.groups.first.name == "Менеджер" or user.groups.first.name == "Сервисная организация" %}
            <th width="3%"></th>
            {% endif %}
        </tr>
    </thead>
    <tbody>
    {% for obj in object_list %}
        <tr>
            <td>{{obj.failure_date|date:"d.m.Y"}}</td>
            <td>{{obj.operating_time}}</td>
            <td><span class="description-js" data-url="{% url 'claim_description' obj.pk 'failure_node' %}">{{obj.failure_node}}</span></td>
            <td>{{obj.failure_description}}</td>
            <td><span class="description-js" data-url="{% url 'claim_description' obj.pk 'recovery_method' %}">{{obj.recovery_method}}</span></td>
            <td>{{obj.spare_parts}}</td>
            <td>{{obj.recovery_date|date:"d.m.Y"}}</td>
            <td>{{obj.downtime}}</td>
            {% if obj.service_company %}
            <td><span class="description-js" data-url="{% url 'claim_description' obj.pk 'service_company' %}">{{obj.service_company}}</span></td>
            {% else %}
            <td>Нет компании</td>
            {% endif %}
            {% if user.is_superuser or user.groups.first.name == "Менеджер" or user.groups.first.name == "Сервисная организация" %}
            <td>
                <div class="actions">
                    <a class="update" href="{% url 'claim_update' obj.pk %}"><i class="fas fa-pencil-alt"></i></a>
                    <a class="delete delete-js" data-url="{% url 'claim_delete' obj.pk %}"><i class="fas fa-times"></i></a>
                </div>
            </td>
            {% endif %}
        </tr>
    {% endfor %}
    </tbody>
</table>
</section>
{% endblock %}

service/templates/service/claim_confirm_delete.html
<a href="" class="modal-area"></a>
<form class="account-form modal-frame" method="post" action="{{request.path}}">
  {% csrf_token %}
    <span class="modal-exit"><i class="fas fa-times"></i></span>
    <div class="modal-body">
        <h1>Удаление</h1>
        {% if redirect_field_value %}
        <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}"/>
        {% endif %}
        <h4>Вы действительно хотите удалить {% if type == 'car' %}погрузчик{% elif type == 'maintenance' %}ТО{% elif type == 'claim' %}рекламацию{% endif %} {{object}}?</h4>
        <div class="modal-buttons">
            <button class="button" type="submit">Удалить</button>
            <span class="dummy-btn"></span>
            <button class="button button-alt cancel-js" type="reset">Отмена</button>
        </div>
    </div>
</form>

service/templates/service/claim_create.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<a class="back-page" href="{% url 'claim_list' %}"><i class="fas fa-long-arrow-alt-left"></i>Назад</a>
<h3>Создание рекламации</h3>
<form class="form" name="claimForm" method="post" action="{{request.path}}">
    {% csrf_token %}
    <div><label for="id_failure_date">{{form.failure_date.label}}</label> {{form.failure_date}}</div>
    <div class="united">
        <label for="id_autocar">{{form.autocar.label}}</label> {{form.autocar}}
        <label for="id_operating_time">{{form.operating_time.label}}</label> {{form.operating_time}}
    </div>
    <div><label for="id_failure_node">{{form.failure_node.label}}</label> {{form.failure_node}}</div>
    <div><label for="id_failure_description">{{form.failure_description.label}}</label> {{form.failure_description}}</div>
    <div><label for="id_recovery_method">{{form.recovery_method.label}}</label> {{form.recovery_method}}</div>
    <div><label for="id_spare_parts">{{form.spare_parts.label}}</label> {{form.spare_parts}}</div>
    <div class="united">
        <label for="id_recovery_date">{{form.recovery_date.label}}</label> {{form.recovery_date}}
        <label for="id_downtime">{{form.downtime.label}}</label> {{form.downtime}}
    </div>
    <div><label for="id_service_company">{{form.service_company.label}}</label> {{form.service_company}}</div>
    <button type="submit">Сохранить</button>
</form>
{% endblock %}

service/templates/service/claim_update.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<a class="back-page" href="{% url 'claim_list' %}"><i class="fas fa-long-arrow-alt-left"></i>Назад</a>
<h3>Изменение рекламации</h3>
<form class="form" name="claimForm" method="post" action="{{request.path}}">
    {% csrf_token %}
    <div><label for="id_failure_date">{{form.failure_date.label}}</label> {{form.failure_date}}</div>
    <div class="united">
        <label for="id_autocar">{{form.autocar.label}}</label> {{form.autocar}}
        <label for="id_operating_time">{{form.operating_time.label}}</label> {{form.operating_time}}
    </div>
    <div><label for="id_failure_node">{{form.failure_node.label}}</label> {{form.failure_node}}</div>
    <div><label for="id_failure_description">{{form.failure_description.label}}</label> {{form.failure_description}}</div>
    <div><label for="id_recovery_method">{{form.recovery_method.label}}</label> {{form.recovery_method}}</div>
    <div><label for="id_spare_parts">{{form.spare_parts.label}}</label> {{form.spare_parts}}</div>
    <div class="united">
        <label for="id_recovery_date">{{form.recovery_date.label}}</label> {{form.recovery_date}}
        <label for="id_downtime">{{form.downtime.label}}</label> {{form.downtime}}
    </div>
    <div><label for="id_service_company">{{form.service_company.label}}</label> {{form.service_company}}</div>
    <button type="submit">Сохранить</button>
</form>
{% endblock %}

service/templates/service/maintenance_car.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<a class="back-page" href="{% url 'car_list' %}"><i class="fas fa-long-arrow-alt-left"></i>Назад</a>
<div class="client">
    <i class="silant silant-vehicle"></i>
    <h2>Погрузчик {{car.serial_number}}</h2>
</div>
<h3>Информация о комплектации и технических характеристиках Вашей техники</h3>
<nav class="nav-panel">
    <ul>
        <li><a href="{% url 'car_detail' car.pk %}"><i class="silant silant-service"></i> Сведения</a></li>
        <li class="active"><a href="{% url 'car_maintenance' car.pk %}"><i class="silant silant-maintenance"></i> ТО</a></li>
        <li><a href="{% url 'car_claim' car.pk %}"><i class="silant silant-complaint"></i> Рекламации</a></li>
    </ul>
</nav>
<div class="action-buttons">
    <a href="{% url 'maintenance_create' %}">Создать ТО</a>
</div>
<section class="area-table"> 
<table id="tableMaintenances" class="datatable" data-order='[0, "desc"]'>
    <thead class="datatable-thead">
        <tr>
            <th width="20%">Дата проведения ТО</th>
            <th width="30%">Вид ТО</th>
            <th width="20%">Наработка, м/час</th>
            <th width="20%">№ заказ-наряда</th>
            <th width="20%">Дата заказ-наряда</th>
            <th width="20%">Организация, проводившая ТО</th>
            <th width="3%"></th>
        </tr>
    </thead>
    <tbody>
    {% for obj in object_list %}
        <tr>
            <td>{{obj.maintenance_date|date:"d.m.Y"}}</td>
            <td><span class="description-js" data-url="{% url 'maintenance_description' obj.pk 'type' %}">{{obj.maintenance_type}}</span></td>
            <td>{{obj.operating_time}}</td>
            <td>{{obj.work_order_number}}</td>
            <td>{{obj.work_order_date|date:"d.m.Y"}}</td>
            {% if obj.service_company %}
            <td><span class="description-js" data-url="{% url 'maintenance_description' obj.pk 'service_company' %}">{{obj.service_company}}</span></td>
            {% else %}
            <td>Нет компании</td>
            {% endif %}
            <td>
                <div class="actions">
                    <a class="update" href="{% url 'maintenance_update' obj.pk %}"><i class="fas fa-pencil-alt"></i></a>
                    <a class="delete delete-js" data-url="{% url 'maintenance_delete' obj.pk %}"><i class="fas fa-times"></i></a>
                </div>
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>
</section>
{% endblock %}

service/templates/service/maintenance_confirm_delete.html
<a href="" class="modal-area"></a>
<form class="account-form modal-frame" method="post" action="{{request.path}}">
  {% csrf_token %}
    <span class="modal-exit"><i class="fas fa-times"></i></span>
    <div class="modal-body">
        <h1>Удаление</h1>
        {% if redirect_field_value %}
        <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}"/>
        {% endif %}
        <h4>Вы действительно хотите удалить {% if type == 'car' %}погрузчик{% elif type == 'maintenance' %}ТО{% elif type == 'complaint' %}рекламацию{% endif %} {{object}}?</h4>
        <div class="modal-buttons">
            <button class="button" type="submit">Удалить</button>
            <span class="dummy-btn"></span>
            <button class="button button-alt cancel-js" type="reset">Отмена</button>
        </div>
    </div>
</form>

service/templates/service/maintenance_create.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<a class="back-page" href="{% url 'maintenance_list' %}"><i class="fas fa-long-arrow-alt-left"></i>Назад</a>
<h2>Создание ТО</h2>
<form class="form" name="maintenanceForm" method="post" action="{{request.path}}">
    {% csrf_token %}
    <div><label for="id_maintenance_date">{{form.maintenance_date.label}}</label> {{form.maintenance_date}}</div>
    <div class="united">
        <label for="id_autocar">{{form.autocar.label}}</label> {{form.autocar}}
        <label for="id_operating_time">{{form.operating_time.label}}</label> {{form.operating_time}}
    </div>
    <div>{{form.maintenance_type.label}}
        <div class="choices"> 
            {% for i, item in form.fields.maintenance_type.widget.choices %}
            <div class="check-field">
                <input type="radio" name="maintenance_type" value="{{i}}" id="id_maintenance_type_{{i}}" {% for item in form.maintenance_type.initial %}{% if i == item.pk %}checked=""{% endif %}{%endfor%}>
                <label for="id_maintenance_type_{{i}}" class="check" name="active-check"><i class="fas fa-check"></i></label>
                <label for="id_maintenance_type_{{i}}" class="check-text">{{item}}</label>
            </div>
            {% endfor %}
        </div> 
    </div>
    <div class="united">
        <label for="id_work_order_number">{{form.work_order_number.label}}</label> {{form.work_order_number}}
        <label for="id_work_order_date">{{form.work_order_date.label}}</label> {{form.work_order_date}}
    </div>
    <div><label for="id_service_company">{{form.service_company.label}}</label> {{form.service_company}}</div>
    <button type="submit">Сохранить</button>
</form>
{% endblock %}

service/templates/service/maintenance_update.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<a class="back-page" href="{% url 'maintenance_list' %}"><i class="fas fa-long-arrow-alt-left"></i>Назад</a>
<h3>Изменение ТО</h3>
<form class="form" name="maintenanceForm" method="post" action="{{request.path}}">
    {% csrf_token %}
    <div><label for="id_maintenance_date">{{form.maintenance_date.label}}</label> {{form.maintenance_date}}</div>
    <div class="united">
        <label for="id_autocar">{{form.autocar.label}}</label> {{form.autocar}}
        <label for="id_operating_time">{{form.operating_time.label}}</label> {{form.operating_time}}
    </div>
    <div>{{form.maintenance_type.label}}
        <div class="choices"> 
            {% for i, item in form.fields.maintenance_type.widget.choices %}
            <div class="check-field">
                <input type="radio" name="maintenance_type" value="{{i}}" id="id_maintenance_type_{{i}}" {% if i == form.maintenance_type.initial%}checked=""{% endif %}>
                <label for="id_maintenance_type_{{i}}" class="check" name="active-check"><i class="fas fa-check"></i></label>
                <label for="id_maintenance_type_{{i}}" class="check-text">{{item}}</label>
            </div>
            {% endfor %}
        </div> 
    </div>
    <div class="united">
        <label for="id_work_order_number">{{form.work_order_number.label}}</label> {{form.work_order_number}}
        <label for="id_work_order_date">{{form.work_order_date.label}}</label> {{form.work_order_date}}
    </div>
    <div><label for="id_service_company">{{form.service_company.label}}</label> {{form.service_company}}</div>
    <button type="submit">Сохранить</button>
</form>
{% endblock %}