forklifts/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('search/', CarSearchView.as_view(), name='car_search_list'),
    path('cars/', CarListView.as_view(), name='car_list'),
    path('car/<pk>/detail', CarDetailView.as_view(), name='car_detail'),
    path('car/create', CarCreateView.as_view(), name='car_create'),
    path('car/<pk>/update', CarUpdateView.as_view(), name='car_update'),
    path('car/<pk>/delete', CarDeleteView.as_view(), name='car_delete'),
    path('car/<pk>/description/<atribute>', CarDescriptionView.as_view(), name='car_description'),

    path('api/cars/',CarListAPI.as_view(),name='car_list_api'),
    path('api/<user>/cars/',CarUserListAPI.as_view(),name='user_car_list_api'),
    path('api/car/<pk>/',CarDetailAPI.as_view(),name='car_detail_api'),
]

service/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

urlpatterns = [
    path('maintenances/', MaintenanceListView.as_view(), name='maintenance_list'),
    path('claims/', ClaimListView.as_view(), name='claim_list'),
    path('car/<pk>/maintenances', MaintenanceCarListView.as_view(), name='car_maintenance'),
    path('car/<pk>/claims', ClaimCarListView.as_view(), name='car_claim'),
    path('maintenance/create', MaintenanceCreateView.as_view(), name='maintenance_create'),
    path('claim/create', ClaimCreateView.as_view(), name='claim_create'),
    path('maintenance/<pk>/update', MaintenanceUpdateView.as_view(), name='maintenance_update'),
    path('claim/<pk>/update', ClaimUpdateView.as_view(), name='claim_update'),
    path('maintenance/<pk>/delete', MaintenanceDeleteView.as_view(), name='maintenance_delete'),
    path('claim/<pk>/delete', ClaimDeleteView.as_view(), name='claim_delete'),
    path('maintenance/<pk>/description/<atribute>', MaintenanceDescriptionView.as_view(),  name='maintenance_description'),
    path('claim/<pk>/description/<atribute>', ClaimDescriptionView.as_view(), name='claim_description'),
    path('api/maintenances/', MaintenanceListAPI.as_view(), name='maintenance_list_api'),
    path('api/<user>/maintenances/', MaintenanceUserListAPI.as_view(), name='user_maintenance_list_api'),
    path('api/maintenance/<pk>/', MaintenanceDetailAPI.as_view(), name='maintenance_detail_api'),
    path('api/claims/', ClaimListAPI.as_view(), name='claim_list_api'),
    path('api/<user>/claims/', ClaimUserListAPI.as_view(), name='user_claim_list_api'),
    path('api/claim/<pk>/', ClaimDetailAPI.as_view(), name='claim_detail_api'),
]

silant_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('service.urls')),
    path('', include('forklifts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

forklifts/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User

class UserAcc(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    is_service = models.BooleanField(default=False, blank=True, verbose_name='Сотрудник сервисной компании')
    service_company = models.ForeignKey(to='service.ServiceCompany', blank=True, null=True, on_delete=models.PROTECT, verbose_name='Сервисная компания')

    def __str__(self):
        return f'{self.user.username} {self.is_service}'
    
    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'


class AutoCar(models.Model):
    serial_number = models.CharField(max_length=16, unique=True, verbose_name='Заводской номер погрузчика')
    car_model = models.ForeignKey('CarModel', on_delete=models.CASCADE, verbose_name='Модель техники')        
    engine_model = models.ForeignKey('EngineModel', on_delete=models.CASCADE, verbose_name='Модель двигателя')
    engine_number = models.CharField(max_length=16, verbose_name='Заводской номер двигателя')
    transmission_model = models.ForeignKey('TransmissionModel', on_delete=models.CASCADE, verbose_name='Модель трансмиссии')
    transmission_number = models.CharField(max_length=16, verbose_name='Заводской номер трансмиссии')
    drive_axle_model = models.ForeignKey('DriveAxleModel', on_delete=models.CASCADE, verbose_name='Модель ведущего моста')
    drive_axle_number = models.CharField(max_length=16, verbose_name='Заводской номер ведущего моста')
    steerable_axle_model = models.ForeignKey('SteerableAxleModel', on_delete=models.CASCADE, verbose_name='Модель управляемого моста')
    steerable_axle_number = models.CharField(max_length=16, verbose_name='Заводской номер управляемого моста')
    supply_contract = models.CharField(max_length=32, verbose_name='Договор поставки №, дата')
    shipment_date = models.DateField(default=datetime.now, verbose_name='Дата отгрузки с завода')
    consumer = models.CharField(max_length=128, verbose_name='Грузополучатель (конечный потребитель)')
    delivery_address = models.CharField(max_length=256, verbose_name='Адрес поставки (эксплуатации)')
    equipment = models.TextField(blank=False, verbose_name='Комплектация (доп. опции)', default="Стандарт")
    client = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Клиент')
    service_company = models.ForeignKey(to='service.ServiceCompany', on_delete=models.CASCADE, verbose_name='Сервисная компания')

    def __str__(self):
        return f'{self.serial_number}'

    class Meta:
        verbose_name = 'Погрузчик'
        verbose_name_plural = 'Погрузчики'

# Справочники

class CarModel(models.Model):
    name = models.CharField(max_length=32, verbose_name='Название')
    description = models.TextField(verbose_name='Описание', blank=True, null=True)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Модель техники'
        verbose_name_plural = 'Модели техники' 

class EngineModel(models.Model):
    name = models.CharField(max_length=32, verbose_name='Название')
    description = models.TextField(verbose_name='Описание', blank=True, null=True)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Модель двигателя'
        verbose_name_plural = 'Модели двигателей' 

class TransmissionModel(models.Model):
    name = models.CharField(max_length=32, verbose_name='Название')
    description = models.TextField(verbose_name='Описание', blank=True, null=True)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Модель трансмиссии'
        verbose_name_plural = 'Модели трансмиссий'  

class DriveAxleModel(models.Model):
    name = models.CharField(max_length=32, verbose_name='Название')
    description = models.TextField(verbose_name='Описание', blank=True, null=True)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Модель ведущего моста'
        verbose_name_plural = 'Модели ведущих мостов' 

class SteerableAxleModel(models.Model):
    name = models.CharField(max_length=32, verbose_name='Название')
    description = models.TextField(verbose_name='Описание', blank=True, null=True)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Модель управляемого моста'
        verbose_name_plural = 'Модели управляемых мостов'    
                                       

forklifts/forms.py
from django import forms
from .models import *

class AutoCarForm(forms.ModelForm):
    class Meta:
        model = AutoCar
        fields = '__all__'

forklifts/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.db.models import Q
from forklifts.models import *
from service.models import *
from forklifts.forms import *
from forklifts.serializers import AutoCarSerializer
from django.contrib.auth.mixins import PermissionRequiredMixin
from rest_framework import generics


# Главная
class HomeView(TemplateView):
    template_name = 'index.html'

    def get(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect('car_list')
        else:
            return redirect('car_search_list')
        

class CarSearchView(ListView):
    model = AutoCar
    template_name = 'forklifts/car_search.html'
    queryset = AutoCar.objects.all()


class CarListView(LoginRequiredMixin, ListView):
    model = AutoCar
    template_name = 'forklifts/car_list.html'

    def get_queryset(self):
        if not self.request.user.is_staff:
            user = User.objects.get(pk=self.request.user.pk)
            try:
                profile = UserAcc.objects.get(user=user)
                if profile.is_service:
                    return AutoCar.objects.filter(service_company=profile.service_company)
            except:
                return AutoCar.objects.filter(client=user)
        else:
            return AutoCar.objects.all()    
        

class CarDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    permission_required = 'forklifts.view_car'
    model = AutoCar
    template_name = 'forklifts/car_view.html'
    context_object_name = 'obj'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context  


class CarCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    permission_required = 'forklifts.add_autocar'
    model = AutoCar
    form_class = AutoCarForm
    template_name = 'forklifts/car_create.html'
    success_url = reverse_lazy('car_list') 


class CarUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    permission_required = 'forklifts.change_autocar'
    model = AutoCar
    form_class = AutoCarForm
    template_name = 'forklifts/car_update.html'
    success_url = reverse_lazy('car_list')  


class CarDescriptionView(TemplateView):
    template_name = 'service/modal_description.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        car = AutoCar.objects.get(pk=self.kwargs["pk"])
        atribute = context['atribute']
        if atribute == 'car_model':
            context['atribute'] = car.car_model
            context['description'] = car.car_model.description
        elif atribute == 'engine_model':
            context['atribute'] = car.engine_model
            context['description'] = car.engine_model.description
        elif atribute == 'transmission_model':
            context['atribute'] = car.transmission_model
            context['description'] = car.transmission_model.description
        elif atribute == 'drive_axle_model':
            context['atribute'] = car.drive_axle_model
            context['description'] = car.drive_axle_model.description
        elif atribute == 'steerable_axle_model':
            context['atribute'] = car.steerable_axle_model
            context['description'] = car.steerable_axle_model.description
        elif atribute == 'equipment':
            context['atribute'] = 'Комплектация'
            context['description'] = car.equipment
        elif atribute == 'service_company':
            context['atribute'] = car.service_company
            context['description'] = car.service_company.description
        return context  


class CarDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    permission_required = 'forklifts.delete_car'
    model = AutoCar
    template_name_suffix = '_confirm_delete'
    success_url = reverse_lazy('car_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["type"] = 'car'
        return context 


# API
class CarListAPI(generics.ListAPIView):
    serializer_class = AutoCarSerializer
    queryset = AutoCar.objects.all()


class CarUserListAPI(generics.ListAPIView):
    serializer_class = AutoCarSerializer

    def get_queryset(self):
        try:
            user = int(self.kwargs['user'])
        except:
            user = self.kwargs['user']
        if type(user) == int:
            queryset = AutoCar.objects.filter(client=user)
        elif type(user) == str:
            queryset = AutoCar.objects.filter(client__username=user)
        return queryset 


class CarDetailAPI(generics.RetrieveAPIView):
    serializer_class = AutoCarSerializer

    def get_object(self):
        obj = AutoCar.objects.get(pk=self.kwargs['pk'])
        return obj                       

forklifts/templates/forklifts/autocar_confirm_delete.html
<a href="" class="modal-area"></a>
<form class="account-form modal-frame" method="post" action="{{request.path}}">
  {% csrf_token %}
    <span class="modal-exit"><i class="fas fa-times"></i></span>
    <div class="modal-body">
        <h1>Удаление</h1>
        {% if redirect_field_value %}
        <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}"/>
        {% endif %}
        <h4>Вы действительно хотите удалить {% if type == 'car' %}погрузчик{% elif type == 'maintenance' %}ТО{% elif type == 'сomplaint' %}рекламацию{% endif %} {{object}}?</h4>
        <div class="modal-buttons">
            <button class="button" type="submit">Удалить</button>
            <span class="dummy-btn"></span>
            <button class="button button-alt cancel-js" type="reset">Отмена</button>
        </div>
    </div>
</form>

forklifts/templates/forklifts/car_create.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<a class="back-page" href="{% url 'car_list' %}"><i class="fas fa-long-arrow-alt-left"></i>Назад</a>
<h3>Создание погрузчика</h3>
<form class="form" name="carForm" method="post" action="{{request.path}}">
    {% csrf_token %}
    <div class="united">
        <label for="id_car_model">{{form.car_model.label}}</label> {{form.car_model}}
        <label for="id_serial_number">{{form.serial_number.label}}</label> {{form.serial_number}}
    </div>
    <div class="united">
        <label for="id_engine_model">{{form.engine_model.label}}</label> {{form.engine_model}}
        <label for="id_engine_number">{{form.engine_number.label}}</label> {{form.engine_number}}
    </div>
    <div class="united">
        <label for="id_transmission_model">{{form.transmission_model.label}}</label> {{form.transmission_model}}
        <label for="id_transmission_number">{{form.transmission_number.label}}</label> {{form.transmission_number}}
    </div>
    <div class="united">
        <label for="id_drive_axle_model">{{form.drive_axle_model.label}}</label> {{form.drive_axle_model}}
        <label for="id_drive_axle_number">{{form.drive_axle_number.label}}</label> {{form.drive_axle_number}}
    </div>
    <div class="united">
        <label for="id_steerable_axle_model">{{form.steerable_axle_model.label}}</label> {{form.steerable_axle_model}}
        <label for="id_steerable_axle_number">{{form.steerable_axle_number.label}}</label> {{form.steerable_axle_number}}
    </div>
    <div class="united">
        <label for="id_supply_contract">{{form.supply_contract.label}}</label> {{form.supply_contract}}
        <label for="id_shipment_date">{{form.shipment_date.label}}</label> {{form.shipment_date}}
    </div>
    <div><label for="id_consumer">{{form.consumer.label}}</label> {{form.consumer}}</div>
    <div><label for="id_delivery_address">{{form.delivery_address.label}}</label> {{form.delivery_address}}</div>
    <div><label for="id_equipment">{{form.equipment.label}}</label> {{form.equipment}}</div>
    <div class="united">
        <label for="id_client">{{form.client.label}}</label> {{form.client}}
        <label for="id_service_company">{{form.service_company.label}}</label> {{form.service_company}}
    </div>
    <button type="submit">Сохранить</button>
</form>
{% endblock %}

forklifts/templates/forklifts/car_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="client">
<i class="silant silant-client"></i>
{% if user.is_superuser %}
    <h2>Администратор</h2>
{% elif user.groups.first.name == "Менеджер" %}
    <h2>Менеджер {{user.first_name}} {{user.last_name}}</h2>
{% elif user.groups.first.name == "Сервисная организация" %}
    <h2>{{user.first_name}} {{user.last_name}} / Сервисная организация {{user.useracc.service_company}}</h2>
{% else %}
    <h2>Клиент {{user.first_name}} {{user.last_name}}</h2>
{% endif %}
</div>
<h3>Информация о комплектации и технических характеристиках Вашей техники</h3>
<nav class="nav-panel">
    <ul>
        <li class="active"><a href="{% url 'car_list' %}"><i class="silant silant-vehicle"></i> Погрузчики</a></li>
        <li><a href="{% url 'maintenance_list' %}"><i class="silant silant-maintenance"></i> ТО</a></li>
        <li><a href="{% url 'claim_list' %}"><i class="silant silant-complaint"></i> Рекламации</a></li>
    </ul>
</nav>
{% if user.is_superuser or user.groups.first.name == "Менеджер" %}
<div class="action-buttons">
    <a href="{% url 'car_create' %}">Добавить погрузчик</a>
</div>
{% else %} 
    <br>
{% endif %}
<section class="area-table"> 
    <table id="tableCars" class="datatable" data-order='[0, "asc"]'>
        <thead class="datatable-thead">
            <tr>
                <th>Зав. № погрузчика</th>
                <th>Модель погрузчика</th>
                <th>Модель двигателя</th>
                <th>Зав. № двигателя</th>
                <th>Модель трансмиссии</th>
                <th>Зав. № трансмиссии</th>
                <th>Модель ведущего моста</th>
                <th>Зав. № ведущего моста</th>
                <th>Модель управляемого моста</th>
                <th>Зав. № управляемого моста</th>
                <th>Договор поставки №, дата</th>
                <th>Дата отгрузки с завода</th>
                <th>Грузополучатель (конечный потребитель)</th>
                <th>Адрес поставки (эксплуатации)</th>
                <th>Комплектация (доп. опции)</th>
                <th>Клиент</th>
                <th>Сервисная компания</th>
                {% if user.is_superuser or user.groups.first.name == "Менеджер" %}
                <th width="3%"></th>
                {% endif %}
            </tr>
        </thead>
        <tbody>
        {% for obj in object_list %}
            <tr>
                <td><a href="{% url 'car_detail' obj.pk %}">{{obj.serial_number}}</a></td>
                <td><span class="description-js" data-url="{% url 'car_description' obj.pk 'car_model' %}">{{obj.car_model}}</span></td>
                <td><span class="description-js" data-url="{% url 'car_description' obj.pk 'engine_model' %}">{{obj.engine_model}}</span></td>
                <td>{{obj.engine_number}}</td>
                <td><span class="description-js" data-url="{% url 'car_description' obj.pk 'transmission_model' %}">{{obj.transmission_model}}</span></td>
                <td>{{obj.transmission_number}}</td>
                <td><span class="description-js" data-url="{% url 'car_description' obj.pk 'drive_axle_model' %}">{{obj.drive_axle_model}}</span></td>
                <td>{{obj.drive_axle_number}}</td>
                <td><span class="description-js" data-url="{% url 'car_description' obj.pk 'steerable_axle_model' %}">{{obj.steerable_axle_model}}</span></td>
                <td>{{obj.steerable_axle_number}}</td>
                <td>{{obj.supply_contract}}</td>
                <td>{{obj.shipment_date|date:"d.m.Y"}}</td>
                <td>{{obj.consumer}}</td>
                <td>{{obj.delivery_address}}</td>
                {% if obj.equipment == 'Стандарт'%}
                <td>{{obj.equipment}}</td>
                {% else %}
                <td><span class="description-js" data-url="{% url 'car_description' obj.pk 'equipment' %}">Посмотреть</span></td>
                {% endif %}
                <td>{{obj.client}}</td>
                {% if obj.service_company %}
                    <td><span class="description-js" data-url="{% url 'car_description' obj.pk 'service_company' %}">{{obj.service_company}}</span></td>
                {% else %}
                    <td>Нет компании</td>
                {% endif %}
                {% if user.is_superuser or user.groups.first.name == "Менеджер" %}
                <td>
                    <div class="actions">
                        <a class="update" href="{% url 'car_update' obj.pk %}"><i class="fas fa-pencil-alt"></i></a>
                        <a class="delete delete-js" data-url="{% url 'car_delete' obj.pk %}"><i class="fas fa-times"></i></a>
                    </div>
                </td>
                {% endif %}
            </tr>
        {% endfor %}
        </tbody>
    </table>
</section>
{% endblock %}

forklifts/templates/forklifts/car_search.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h4>Проверьте комплектацию и технические характеристики техники Силант</h4>
<form id="search" class="search" method="get">
    <input id="search-input" type="search" name="q" placeholder="Введите заводской номер погрузчика">
    <button id="search-button" type="button">Найти</button>
</form>
<h3>Информация о комплектации и технических характеристиках Вашей техники</h3>
<section class="area-table"> 
    <table id="tableCars" class="datatable" data-order='[0, "asc"]'>
        <thead class="datatable-thead">
            <tr>
                <th>Зав. № погрузчика</th>
                <th>Модель погрузчика</th>
                <th>Модель двигателя</th>
                <th>Зав. № двигателя</th>
                <th>Модель трансмиссии</th>
                <th>Зав. № трансмиссии</th>
                <th>Модель ведущего моста</th>
                <th>Зав. № ведущего моста</th>
                <th>Модель управляемого моста</th>
                <th>Зав. № управляемого моста</th>
            </tr>
        </thead>
        <tbody>
        {% for obj in object_list %}
            <tr>
                <td>{{obj.serial_number}}</td>
                <td><span class="description-js" data-url="{% url 'car_description' obj.pk 'car_model' %}">{{obj.car_model}}</span></td>
                <td><span class="description-js" data-url="{% url 'car_description' obj.pk 'engine_model' %}">{{obj.engine_model}}</span></td>
                <td>{{obj.engine_number}}</td>
                <td><span class="description-js" data-url="{% url 'car_description' obj.pk 'transmission_model' %}">{{obj.transmission_model}}</span></td>
                <td>{{obj.transmission_number}}</td>
                <td><span class="description-js" data-url="{% url 'car_description' obj.pk 'drive_axle_model' %}">{{obj.drive_axle_model}}</span></td>
                <td>{{obj.drive_axle_number}}</td>
                <td><span class="description-js" data-url="{% url 'car_description' obj.pk 'steerable_axle_model' %}">{{obj.steerable_axle_model}}</span></td>
                <td>{{obj.steerable_axle_number}}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</section>
{% endblock %}

forklifts/templates/forklifts/car_update.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<a class="back-page" href="{% url 'car_list' %}"><i class="fas fa-long-arrow-alt-left"></i>Назад</a>
<h3>Изменение параметров погрузчика</h3>
<form class="form" name="carForm" method="post" action="{{request.path}}">
    {% csrf_token %}
    <div class="united">
        <label for="id_car_model">{{form.car_model.label}}</label> {{form.car_model}}
        <label for="id_serial_number">{{form.serial_number.label}}</label> {{form.serial_number}}
    </div>
    <div class="united">
        <label for="id_engine_model">{{form.engine_model.label}}</label> {{form.engine_model}}
        <label for="id_engine_number">{{form.engine_number.label}}</label> {{form.engine_number}}
    </div>
    <div class="united">
        <label for="id_transmission_model">{{form.transmission_model.label}}</label> {{form.transmission_model}}
        <label for="id_transmission_number">{{form.transmission_number.label}}</label> {{form.transmission_number}}
    </div>
    <div class="united">
        <label for="id_drive_axle_model">{{form.drive_axle_model.label}}</label> {{form.drive_axle_model}}
        <label for="id_drive_axle_number">{{form.drive_axle_number.label}}</label> {{form.drive_axle_number}}
    </div>
    <div class="united">
        <label for="id_steerable_axle_model">{{form.steerable_axle_model.label}}</label> {{form.steerable_axle_model}}
        <label for="id_steerable_axle_number">{{form.steerable_axle_number.label}}</label> {{form.steerable_axle_number}}
    </div>
    <div class="united">
        <label for="id_supply_contract">{{form.supply_contract.label}}</label> {{form.supply_contract}}
        <label for="id_shipment_date">{{form.shipment_date.label}}</label> {{form.shipment_date}}
    </div>
    <div><label for="id_consumer">{{form.consumer.label}}</label> {{form.consumer}}</div>
    <div><label for="id_delivery_address">{{form.delivery_address.label}}</label> {{form.delivery_address}}</div>
    <div><label for="id_equipment">{{form.equipment.label}}</label> {{form.equipment}}</div>
    <div class="united">
        <label for="id_client">{{form.client.label}}</label> {{form.client}}
        <label for="id_service_company">{{form.service_company.label}}</label> {{form.service_company}}
    </div>
    <button type="submit">Сохранить</button>
</form>
{% endblock %}

forklifts/templates/forklifts/car_view.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<a class="back-page" href="{% url 'car_list' %}"><i class="fas fa-long-arrow-alt-left"></i>Назад</a>
<div class="client">
    <i class="silant silant-vehicle"></i>
    <h2>Погрузчик {{obj.serial_number}}</h2>
</div>
<h3>Информация о комплектации и технических характеристиках Вашей техники</h3>
<nav class="nav-panel">
    <ul>
        <li class="active"><a href="{% url 'car_detail' obj.pk %}"><i class="silant silant-service"></i> Информация</a></li>
        <li><a href="{% url 'car_maintenance' obj.pk %}"><i class="silant silant-maintenance"></i> ТО</a></li>
        <li><a href="{% url 'car_claim' obj.pk %}"><i class="silant silant-complaint"></i> Рекламации</a></li>
    </ul>
</nav><br><br>
<section class="area-table"> 
<table id="tableCars" class="datatable" data-order='[[11, "desc"],[0, "desc"]]'>
    <thead class="datatable-thead">
        <tr>
            <th>Модель погрузчика</th>
            <th>Модель двигателя</th>
            <th>Зав. № двигателя</th>
            <th>Модель трансмиссии</th>
            <th>Зав. № трансмиссии</th>
            <th>Модель ведущего моста</th>
            <th>Зав. № ведущего моста</th>
            <th>Модель управляемого моста</th>
            <th>Зав. № управляемого моста</th>
            <th>Договор поставки №, дата</th>
            <th>Дата отгрузки с завода</th>
            <th>Грузополучатель (конечный потребитель)</th>
            <th>Адрес поставки (эксплуатации)</th>
            <th>Комплектация (доп. опции)</th>
            <th>Клиент</th>
            <th>Сервисная компания</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><span class="description-js" data-url="{% url 'car_description' obj.pk 'car_model' %}">{{obj.car_model}}</span></td>
            <td><span class="description-js" data-url="{% url 'car_description' obj.pk 'engine_model' %}">{{obj.engine_model}}</span></td>
            <td>{{obj.engine_number}}</td>
            <td><span class="description-js" data-url="{% url 'car_description' obj.pk 'transmission_model' %}">{{obj.transmission_model}}</span></td>
            <td>{{obj.transmission_number}}</td>
            <td><span class="description-js" data-url="{% url 'car_description' obj.pk 'drive_axle_model' %}">{{obj.drive_axle_model}}</span></td>
            <td>{{obj.drive_axle_number}}</td>
            <td><span class="description-js" data-url="{% url 'car_description' obj.pk 'steerable_axle_model' %}">{{obj.steerable_axle_model}}</span></td>
            <td>{{obj.steerable_axle_number}}</td>
            <td>{{obj.supply_contract}}</td>
            <td>{{obj.shipment_date}}</td>
            <td>{{obj.consumer}}</td>
            <td>{{obj.delivery_address}}</td>
            {% if obj.equipment == 'Стандарт'%}
                <td>{{obj.equipment}}</td>
            {% else %}
                <td><span class="description-js" data-url="{% url 'car_description' obj.pk 'equipment' %}">Посмотреть</span></td>
            {% endif %}
            <td>{{obj.client}}</td>
            {% if obj.service_company %}
                <td><span class="description-js" data-url="{% url 'maintenance_description' obj.pk 'service_company' %}">{{obj.service_company}}</span></td>
            {% else %}
                <td>Нет компании</td>
            {% endif %}
        </tr>
    </tbody>
</table>
</section>

{% endblock %}